- name: upgrade java from java-7 to java-8
  hosts: all
  become: yes
  tasks:
  - name: Install java-8 on Amazon Linux2
    yum:
      name: java-1.8*
      state: present
    register: amzn
  - name: check outcome
    debug:
      msg: "{{amzn}}"          
  - name: select desired java version
    alternatives:
      name: java
      path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.412.b08-1.amzn2.0.1.x86_64/bin/java
      link: /usr/bin/java
  - name: update JAVA_HOME
    lineinfile:
      path: /etc/profile
      regexp: '^JAVA_HOME='
      line: 'JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.412.b08-1.amzn2.0.1.x86_64"'
  - name: update PATH
    lineinfile: 
      path: /etc/profile
      regexp: '^PATH='
      line: 'PATH="$PATH:$JAVA_HOME/bin:/usr/local/bin"'
  - name: Show Java Version
    shell: java -version 
